CREATE TABLE PRODUCTO(
	ID_PRODUCTO INT NOT NULL,
	NOMBRE VARCHAR(20),
	
	CONSTRAINT PK_PRODUCTO PRIMARY KEY (ID_PRODUCTO)
);

CREATE TABLE VENTA(
	ID_VENTA INT NOT NULL,
	ID_PRODUCTO INT NOT NULL,
	CANTIDAD INT NOT NULL,
	
	CONSTRAINT PK_VENTA PRIMARY KEY (ID_VENTA),
	CONSTRAINT FK_VENTA_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO)
);

CREATE TABLE STOCK(
	ID_STOCK INT NOT NULL,
	ID_PRODUCTO INT NOT NULL,
	CANTIDAD INT NOT NULL,
	
	CONSTRAINT PK_STOCK PRIMARY KEY (ID_STOCK),
	CONSTRAINT FK_STOCK_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO)
);

CREATE TABLE COMPRA(
	ID_COMPRA INT NOT NULL,
	ID_PRODUCTO INT NOT NULL,
	CANTIDAD INT NOT NULL,
	
	CONSTRAINT PK_COMPRA PRIMARY KEY (ID_COMPRA),
	CONSTRAINT FK_COMPRA_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO)
);
