delimiter //

CREATE PROCEDURE SumarStockDirty(IN PRODUCTO int, OUT NEW_STOCK int)
	LANGUAGE SQL
	NOT DETERMINISTIC
	CONTAINS SQL
	SQL SECURITY DEFINER
	COMMENT ''
BEGIN
	start transaction;
	set @TOTAL_COMPRAS = 0 ;
	set @COMPRAS_AUX = 0 ;
	SELECT sum(CANTIDAD) INTO @TOTAL_COMPRAS FROM COMPRA WHERE COMPRA.ID_PRODUCTO = PRODUCTO;
	IF (@TOTAL_COMPRAS) <> NULL then 
	BEGIN
		SELECT CANTIDAD INTO @COMPRAS_AUX FROM STOCK WHERE STOCK.ID_PRODUCTO = PRODUCTO;
		set NEW_STOCK = @CANTIDAD_AUX + @TOTAL_COMPRAS ;
		update STOCK set CANTIDAD = NEW_STOCK WHERE STOCK.ID_PRODUCTO = PRODUCTO;
		select sleep(10) ;
		update COMPRA set CANTIDAD = 0 where COMPRA.ID_PRODUCTO = PRODUCTO ;
	END;
	END IF;
	rollback;
END //

delimiter ;
