CREATE TABLE LIBRO 
(
    ISBN INTEGER NOT NULL PRIMARY KEY,
    TITULO VARCHAR(20) NOT NULL

);

CREATE TABLE EJEMPLAR
(
    NUMERO_EJEMPLAR INTEGER NOT NULL,
    ISBN INTEGER NOT NULL,
    
    CONSTRAINT PK_EJEMPLAR PRIMARY KEY (ISBN,NUMERO_EJEMPLAR),
    CONSTRAINT FK_EJEMPLAR_LIBRO FOREIGN KEY (ISBN) REFERENCES LIBRO
);

CREATE TABLE AXLIBRO
(
    ISBN INTEGER NOT NULL PRIMARY KEY,
    SIGUIENTE_NUMERO_EJEMPLAR INTEGER NOT NULL
);


SET TERM ^ ; 
CREATE TRIGGER TRG_AILIBRO FOR LIBRO
ACTIVE 
AFTER INSERT 
POSITION 0
AS
BEGIN 
    INSERT INTO AXLIBRO (ISBN,SIGUIENTE_NUMERO_EJEMPLAR) VALUES (NEW.ISBN,0);

END^
SET TERM ; ^

SET TERM ^ ; 
CREATE TRIGGER TRG_BIEJEMPLAR FOR EJEMPLAR
ACTIVE 
BEFORE INSERT 
POSITION 0
AS
    DECLARE AXSIGUIENTE_NUMERO_EJEMPLAR INTEGER;
BEGIN 
    AXSIGUIENTE_NUMERO_EJEMPLAR = (SELECT SIGUIENTE_NUMERO_EJEMPLAR
                                    FROM AXLIBRO
                                    WHERE ISBN=NEW.ISBN);
    NEW.NUMERO_EJEMPLAR = AXSIGUIENTE_NUMERO_EJEMPLAR;
END^
SET TERM ; ^

SET TERM ^ ; 
CREATE TRIGGER TRG_AIEJEMPLAR FOR EJEMPLAR
ACTIVE 
AFTER INSERT 
POSITION 0
AS
BEGIN 
    UPDATE AXLIBRO
    SET SIGUIENTE_NUMERO_EJEMPLAR = SIGUIENTE_NUMERO_EJEMPLAR+1
    WHERE ISBN = NEW.ISBN;
END^
SET TERM ; ^


-- SEGURIDAD

CREATE USER AGUSTINEJ4
   PASSWORD 'asdasd'
   FIRSTNAME 'Agustin'
   MIDDLENAME ''
   LASTNAME 'Normand';

CREATE ROLE USUARIO;

GRANT USUARIO TO AGUSTINEJ4;

GRANT SELECT ON LIBRO TO USUARIO;

GRANT UPDATE ON LIBRO TO USUARIO;

GRANT INSERT ON LIBRO TO USUARIO;

GRANT DELETE ON LIBRO TO USUARIO;

GRANT SELECT ON EJEMPLAR TO USUARIO;

GRANT UPDATE ON EJEMPLAR TO USUARIO;

GRANT INSERT ON EJEMPLAR TO USUARIO;

GRANT DELETE ON EJEMPLAR TO USUARIO;

GRANT ALL ON AXLIBRO TO TRIGGER TRG_AILIBRO;

GRANT ALL ON AXLIBRO TO TRIGGER TRG_BIEJEMPLAR;

GRANT ALL ON AXLIBRO TO TRIGGER TRG_AIEJEMPLAR;
--

