


-- ## SP_SELECT_PROCEDURE_1Y2

GRANT EXECUTE ON PROCEDURE SP_SELECT_PROCEDURE_1Y2 TO USUARIO;

GRANT ALL ON FACTURA TO PROCEDURE SP_SELECT_PROCEDURE_1Y2;



-- ## SP_SELECT_PROCEDURE_3

GRANT EXECUTE ON PROCEDURE SP_SELECT_PROCEDURE_3 TO USUARIO;

GRANT ALL ON PRODUCTO TO PROCEDURE SP_SELECT_PROCEDURE_3;

GRANT ALL ON FACTURA TO PROCEDURE SP_SELECT_PROCEDURE_3;

GRANT ALL ON DETALLE TO PROCEDURE SP_SELECT_PROCEDURE_3;



-- ## SP_SELECT_PROCEDURE_4

GRANT EXECUTE ON PROCEDURE SP_SELECT_PROCEDURE_4 TO USUARIO;

GRANT ALL ON PRODUCTO TO PROCEDURE SP_SELECT_PROCEDURE_4;

GRANT ALL ON DETALLE TO PROCEDURE SP_SELECT_PROCEDURE_4;



-- ## SP_SELECT_PROCEDURE_5

GRANT EXECUTE ON PROCEDURE SP_SELECT_PROCEDURE_5 TO USUARIO;

GRANT ALL ON FACTURA TO PROCEDURE SP_SELECT_PROCEDURE_5;



-- ## SP_SELECT_PROCEDURE_6

GRANT EXECUTE ON PROCEDURE SP_SELECT_PROCEDURE_6 TO USUARIO;

GRANT ALL ON DETALLE TO PROCEDURE SP_SELECT_PROCEDURE_6;

GRANT ALL ON PRODUCTO TO PROCEDURE SP_SELECT_PROCEDURE_6;

GRANT ALL ON FACTURA TO PROCEDURE SP_SELECT_PROCEDURE_6;



-- ## SP_SELECT_PROCEDURE_7

GRANT EXECUTE ON PROCEDURE SP_SELECT_PROCEDURE_7 TO USUARIO;

GRANT ALL ON FACTURA TO PROCEDURE SP_SELECT_PROCEDURE_7;



-- ## SP_EXECUTE_PROCEDURE_1

GRANT EXECUTE ON PROCEDURE SP_EXECUTE_PROCEDURE_1 TO USUARIO;

GRANT ALL ON FACTURA TO PROCEDURE SP_EXECUTE_PROCEDURE_1;



-- ## SP_EXECUTE_PROCEDURE_2 

GRANT EXECUTE ON PROCEDURE SP_EXECUTE_PROCEDURE_2 TO USUARIO;

GRANT ALL ON PRODUCTO TO PROCEDURE SP_EXECUTE_PROCEDURE_2;



-- ## SP_EXECUTE_PROCEDURE_3

GRANT EXECUTE ON PROCEDURE SP_EXECUTE_PROCEDURE_3 TO USUARIO;

GRANT ALL ON FACTURA TO PROCEDURE SP_EXECUTE_PROCEDURE_3;

