CREATE TABLE CLIENTE(
	IDC INT NOT NULL,
	DESCR VARCHAR(20) NOT NULL,
	TIVA INT NOT NULL,
	
	CONSTRAINT PK_CLIENTE PRIMARY KEY (IDC)
);

CREATE TABLE FACTURA(
	NRO INT NOT NULL,
	IDC INT NOT NULL,
	FECHA DATE NOT NULL,
    ESTADO INT DEFAULT 0,
	
	CONSTRAINT PK_FACTURA PRIMARY KEY (NRO),
	CONSTRAINT FK_FACTURA_CLIENTE FOREIGN KEY (IDC) REFERENCES CLIENTE
);

CREATE TABLE FACTURA_AUX(
	NRO INT NOT NULL,
	NETO INT DEFAULT 0,
	IVA1 FLOAT DEFAULT 0,
	IVA2 FLOAT DEFAULT 0,
	MONTO FLOAT DEFAULT 0,
	
	CONSTRAINT PK_FACTURA_AUX PRIMARY KEY (NRO)
);

CREATE TABLE PRODUCTO(
	IDP INT NOT NULL,
	PRECIO_BASE FLOAT NOT NULL,
	
	CONSTRAINT PK_PRODUCTO PRIMARY KEY (IDP)
);

CREATE TABLE DETALLE(
	NRO INT NOT NULL,
	IDP INT NOT NULL,
	CANT INT NOT NULL,
	PRECIO FLOAT NOT NULL,
	
	CONSTRAINT PK_DETALLE PRIMARY KEY (NRO,IDP),
	CONSTRAINT FK_DETALLE_PRODUCTO FOREIGN KEY (IDP) REFERENCES PRODUCTO,
	CONSTRAINT FK_DETALLE_FACTURA FOREIGN KEY (NRO) REFERENCES FACTURA
);

CREATE EXCEPTION EX_CLAVE_PRIMARIA 'No es posible modificar la clave primaria';
CREATE EXCEPTION EX_FALTAN_DETALLES 'No se puede terminar una factura con menos de 1 detalle';
CREATE EXCEPTION EX_FACTURA_TERMINADA 'No se puede modificar un detalle o cliente de una factura terminada';

SET TERM ^ ;

CREATE TRIGGER TRG_AIFACTURA FOR FACTURA
ACTIVE
AFTER INSERT
POSITION 0
AS
BEGIN
INSERT INTO FACTURA_AUX(NRO) VALUES (NEW.NRO);
END^

CREATE TRIGGER TRG_BUFACTURA FOR FACTURA
ACTIVE
BEFORE UPDATE
POSITION 0
AS
BEGIN
	IF(NEW.NRO <> OLD.NRO) THEN
		EXCEPTION EX_CLAVE_PRIMARIA;
	IF(NEW.ESTADO <> OLD.ESTADO AND NEW.ESTADO = 1) THEN
		IF(NOT EXISTS(SELECT * FROM DETALLE WHERE NRO = NEW.NRO)) THEN
			EXCEPTION EX_FALTAN_DETALLES;
END^

CREATE TRIGGER TRG_AUFACTURA FOR FACTURA
ACTIVE
AFTER UPDATE
POSITION 0
AS
	DECLARE TIPO_IVA_CLIENTE INT;
	DECLARE NETO FLOAT;
BEGIN
	IF ((NEW.ESTADO <> OLD.ESTADO) AND NEW.ESTADO = 1) THEN
	BEGIN
		TIPO_IVA_CLIENTE = (SELECT TIVA FROM CLIENTE WHERE IDC = NEW.IDC);
		NETO = (SELECT SUM(CANT*PRECIO) FROM DETALLE WHERE NRO = NEW.NRO);
		UPDATE FACTURA_AUX SET NETO = :NETO WHERE NRO = NEW.NRO;
		
		IF(TIPO_IVA_CLIENTE = 1 OR TIPO_IVA_CLIENTE = 2 OR TIPO_IVA_CLIENTE = 4) THEN
			UPDATE FACTURA_AUX SET IVA1 = :NETO * 0.21 WHERE NRO = NEW.NRO;
		ELSE
			UPDATE FACTURA_AUX SET IVA1 = 0 WHERE NRO = NEW.NRO;
		IF(TIPO_IVA_CLIENTE = 4) THEN
			UPDATE FACTURA_AUX SET IVA2 = (:NETO * 10.5) / 100 WHERE NRO = NEW.NRO;
		ELSE
			UPDATE FACTURA_AUX SET IVA2 = 0 WHERE NRO = NEW.NRO;
			
		UPDATE FACTURA_AUX SET MONTO = NETO + IVA1 + IVA2 WHERE NRO = NEW.NRO;
	END
	
	IF ((NEW.ESTADO <> OLD.ESTADO) AND NEW.ESTADO = 0) THEN -- SI VOLVIO AL ESTADO INICIAL
		UPDATE FACTURA_AUX SET MONTO = 0, NETO = 0, IVA1 = 0, IVA2 = 0 WHERE NRO = NEW.NRO; --PONGO TODO EN 0
	
END^

CREATE TRIGGER TRG_ADFACTURA FOR FACTURA
ACTIVE
AFTER DELETE
POSITION 0
AS
BEGIN
	DELETE FROM FACTURA_AUX WHERE NRO = OLD.NRO;
END^

CREATE TRIGGER TRG_BUDETALLE FOR DETALLE
ACTIVE
BEFORE UPDATE
POSITION 0
AS
BEGIN
	IF(NEW.NRO <> OLD.NRO OR NEW.IDP <> OLD.IDP) THEN
		EXCEPTION EX_CLAVE_PRIMARIA;
	IF(NEW.CANT <> OLD.CANT OR NEW.PRECIO <> OLD.PRECIO) THEN
		IF((SELECT ESTADO FROM FACTURA WHERE NRO = NEW.NRO) = 1) THEN
			EXCEPTION EX_FACTURA_TERMINADA;
END^

CREATE TRIGGER TRG_BUCLIENTE FOR CLIENTE
ACTIVE
BEFORE UPDATE
POSITION 0
AS
BEGIN
	IF (NEW.IDC <> OLD.IDC) THEN
		EXCEPTION EX_CLAVE_PRIMARIA;
	IF (NEW.TIVA <> OLD.TIVA) THEN
		IF(EXISTS(SELECT * FROM FACTURA WHERE IDC = NEW.IDC AND ESTADO = 1)) THEN
			EXCEPTION EX_FACTURA_TERMINADA;
END^

SET TERM ; ^
CREATE ROLE ROLE_USUARIO;

CREATE USER USUARIO PASSWORD 'asdasd';

GRANT ROLE_USUARIO TO USUARIO;

GRANT SELECT ON FACTURA TO ROLE_USUARIO;

GRANT UPDATE ON FACTURA TO ROLE_USUARIO;

GRANT DELETE ON FACTURA TO ROLE_USUARIO;

GRANT INSERT ON FACTURA TO ROLE_USUARIO;

GRANT SELECT ON DETALLE TO ROLE_USUARIO;

GRANT UPDATE ON DETALLE TO ROLE_USUARIO;

GRANT DELETE ON DETALLE TO ROLE_USUARIO;

GRANT INSERT ON DETALLE TO ROLE_USUARIO;

GRANT SELECT ON CLIENTE TO ROLE_USUARIO;

GRANT UPDATE ON CLIENTE TO ROLE_USUARIO;

GRANT DELETE ON CLIENTE TO ROLE_USUARIO;

GRANT INSERT ON CLIENTE TO ROLE_USUARIO;

GRANT SELECT ON PRODUCTO TO ROLE_USUARIO;

GRANT UPDATE ON PRODUCTO TO ROLE_USUARIO;

GRANT DELETE ON PRODUCTO TO ROLE_USUARIO;

GRANT INSERT ON PRODUCTO TO ROLE_USUARIO;

GRANT SELECT ON FACTURA_AUX TO ROLE_USUARIO;

GRANT ALL ON FACTURA_AUX TO TRIGGER TRG_AIFACTURA;

GRANT ALL ON DETALLE TO TRIGGER TRG_BUFACTURA;

GRANT ALL ON CLIENTE TO TRIGGER TRG_AUFACTURA;

GRANT ALL ON DETALLE TO TRIGGER TRG_AUFACTURA;

GRANT ALL ON FACTURA_AUX TO TRIGGER TRG_AUFACTURA;

GRANT ALL ON FACTURA_AUX TO TRIGGER TRG_ADFACTURA;

GRANT ALL ON FACTURA TO TRIGGER TRG_BUCLIENTE;
--------------------------------------------------
INSERT INTO CLIENTE(IDC,DESCR,TIVA) VALUES (1,'A',1);

INSERT INTO FACTURA(NRO,IDC,FECHA) VALUES(1,1,CURRENT_DATE);

UPDATE FACTURA SET ESTADO = 1 WHERE NRO = 1;

INSERT INTO PRODUCTO(IDP,PRECIO_BASE) VALUES (1,100);

INSERT INTO DETALLE(NRO,IDP,CANT,PRECIO) VALUES(1,1,10,100);

UPDATE DETALLE SET CANT = 1 WHERE NRO = 1;

UPDATE CLIENTE SET TIVA = 3 WHERE IDC = 1;
