-- TESTING

EXECUTE PROCEDURE SP_PRODUCTO ('I',1,100);
EXECUTE PROCEDURE SP_PRODUCTO ('I',2,200);
EXECUTE PROCEDURE SP_PRODUCTO ('I',3,300);
EXECUTE PROCEDURE SP_PRODUCTO ('I',4,400);
EXECUTE PROCEDURE SP_PRODUCTO ('I',5,500);

EXECUTE PROCEDURE SP_FACTURA ('I',1,1000);
EXECUTE PROCEDURE SP_FACTURA ('I',2,2000);

EXECUTE PROCEDURE SP_DETALLE ('I',1,1,'A');
EXECUTE PROCEDURE SP_DETALLE ('I',1,2,'B');
EXECUTE PROCEDURE SP_DETALLE ('I',1,3,'C');
EXECUTE PROCEDURE SP_DETALLE ('I',2,1,'A');
EXECUTE PROCEDURE SP_DETALLE ('I',2,2,'B');
EXECUTE PROCEDURE SP_DETALLE ('I',2,3,'C');

-- DETALLES_RESTANTES EN FACTURAS DEBERIAN TENER 0 EN DETALLES_RESTANTES

EXECUTE PROCEDURE SP_DETALLE ('D',1,1,'DELETE');

-- DETALLES_RESTANTES EN FACTURAS WHERE NRO = 1 DEBERIA TENER 1 EN DETALLES_RESTANTES

EXECUTE PROCEDURE SP_DETALLE ('D',2,3,'DELETE');

EXECUTE PROCEDURE SP_DETALLE ('I',1,1,'INSERTED');

-- DETALLES_RESTANTES EN FACTURAS WHERE NRO = 1 DEBERIA TENER 0 EN DETALLES_RESTANTES y WHERE NRO = 2 DEBERIA TENER 1 EN DETALLES_RESTANTES

EXECUTE PROCEDURE SP_DETALLE ('U',1,2,'CHANGED');

-- DETALLES_RESTANTES EN FACTURAS NO DEBERIA CAMBIAR, 1 DEBERIA ESTAR EN 0 Y 2 DEBERIA ESTAR EN 1

EXECUTE PROCEDURE SP_FACTURA ('D',1);

-- NO DEBERIA DEJARME SI HAY DETALLES.
