SET TERM ^ ;

CREATE PROCEDURE EJEMPLO_7
(
   NOMBRE_TABLA VARCHAR(30)
)
AS
   DECLARE COMANDO VARCHAR(512);
BEGIN
   COMANDO = 'CREATE TABLE ' || :NOMBRE_TABLA ||
             '(DNI INTEGER NOT NULL,
              NOMBRE VARCHAR(30) NOT NULL,
              CONSTRAINT PK_' || :NOMBRE_TABLA || ' PRIMARY KEY (DNI));';

   EXECUTE STATEMENT :COMANDO;   
   
   EXECUTE STATEMENT :COMANDO WITH COMMON TRANSACTION
   ON EXTERNAL '192.168.0.29/3050:/var/lib/firebird/2.5/data/dbDebian1.fdb'
   AS USER 'SYSDBA' PASSWORD 'masterkey';

   EXECUTE STATEMENT :COMANDO WITH COMMON TRANSACTION
   ON EXTERNAL '192.168.0.5/3050:/var/lib/firebird/2.5/data/dbDebian2.fdb'
   AS USER 'SYSDBA' PASSWORD 'masterkey';
END^

SET TERM ; ^ 
