SET TERM ^ ;
CREATE PROCEDURE CREARTABLA_PERSONA_DEB1
AS
   DECLARE COMANDO VARCHAR(512);
BEGIN
   COMANDO = ' CREATE TABLE PERSONA
               (
               DNI INTEGER NOT NULL,
               NOMBRE VARCHAR(20) NOT NULL,
               CONSTRAINT PK_PERSONA PRIMARY KEY (DNI)
               ); ';
   EXECUTE STATEMENT :COMANDO WITH COMMON TRANSACTION 
   ON EXTERNAL '192.168.0.29/3050:/var/lib/firebird/2.5/data/dbDebian1.fdb'
   AS USER 'SYSDBA' PASSWORD 'masterkey';
END^
SET TERM ; ^
