SET TERM ^ ;
CREATE TRIGGER TRG_ADPERSONA FOR PERSONA
ACTIVE
AFTER DELETE
POSITION 0
AS
   DECLARE COMANDO VARCHAR(512);
BEGIN
   COMANDO = 'DELETE FROM PERSONA WHERE DNI = ' || OLD.DNI;
   EXECUTE STATEMENT :COMANDO WITH AUTONOMOUS TRANSACTION
   ON EXTERNAL '192.168.0.29/3050:/var/lib/firebird/2.5/data/dbDebian1.fdb'
   AS USER 'SYSDBA' PASSWORD 'masterkey';
END^

SET TERM ; ^
