INSERT INTO RUBRO(CodRub,NomRub) VALUES (1,'RubUno');
INSERT INTO RUBRO(CodRub,NomRub) VALUES (2,'RubDos');
INSERT INTO RUBRO(CodRub,NomRub) VALUES (3,'RubTres');
INSERT INTO RUBRO(CodRub,NomRub) VALUES (4,'RubCuatro');

INSERT INTO PRODUCTO(CodRub,CodPro,NomPro) VALUES (1,1,'ProdUnoUno');
INSERT INTO PRODUCTO(CodRub,CodPro,NomPro) VALUES (2,1,'ProdDosUno');
INSERT INTO PRODUCTO(CodRub,CodPro,NomPro) VALUES (2,2,'ProdDosDos');
INSERT INTO PRODUCTO(CodRub,CodPro,NomPro) VALUES (3,1,'ProdTresUno');
