-- TESTING

INSERT INTO PRODUCTO
VALUES(1,100);

INSERT INTO PRODUCTO
VALUES(2,200);

INSERT INTO PRODUCTO
VALUES(3,300);

INSERT INTO PRODUCTO
VALUES(4,400);

INSERT INTO PRODUCTO
VALUES(5,500);

INSERT INTO FACTURA
VALUES(1,1000);

INSERT INTO FACTURA
VALUES(2,2000);

INSERT INTO DETALLE
VALUES (1,1,'A');

INSERT INTO DETALLE
VALUES (1,2,'B');

INSERT INTO DETALLE
VALUES (1,3,'C');

INSERT INTO DETALLE
VALUES (2,1,'A');

INSERT INTO DETALLE
VALUES (2,2,'B');

INSERT INTO DETALLE
VALUES (2,3,'C');

-- AXFACTURAS DEBERIAN TENER 0 EN DETALLES_RESTANTES

DELETE FROM DETALLE
WHERE ID = 1 AND NRO = 1;

-- AXFACTURAS WHERE NRO = 1 DEBERIA TENER 1 EN DETALLES_RESTANTES

UPDATE DETALLE
SET NRO = 1
WHERE NRO = 2 AND ID = 1;

-- AXFACTURAS WHERE NRO = 1 DEBERIA TENER 0 EN DETALLES_RESTANTES y WHERE NRO = 2 DEBERIA TENER 1 EN DETALLES_RESTANTES

UPDATE DETALLE
SET DESCRIPCION = 'CHANGED'
WHERE NRO = 1 AND ID = 2;

-- AXFACTURAS NO DEBERIA CAMBIAR, 1 DEBERIA ESTAR EN 0 Y 2 DEBERIA ESTAR EN 1

DELETE FROM FACTURA
WHERE NRO = 1;

-- DEBERIA TIRAR ERROR PORQUE DEBO BORRAR LOS DETALLES

DELETE FROM DETALLE
WHERE NRO = 1;

DELETE FROM FACTURA
WHERE NRO = 1;

-- DEBERIA BORRAR LA TUPLA DE AXFACTURA

UPDATE FACTURA
SET NRO = 3
WHERE NRO = 1;

-- NO DEBERIA DEJARME
