CREATE TABLE PERSONA(
	DNI INT NOT NULL, 
	NOMBRE VARCHAR(30) NOT NULL,
	
	CONSTRAINT PK_PERSONA PRIMARY KEY (DNI)
);

CREATE TABLE EMPLEADO(
	DNI INT NOT NULL,

	CONSTRAINT PK_EMPLEADO PRIMARY KEY (DNI),
	CONSTRAINT FK_EMPLEADO_PERSONA FOREIGN KEY (DNI) REFERENCES PERSONA
);

CREATE TABLE CONTRATISTA(
	DNI INT NOT NULL,

	CONSTRAINT PK_CONTRATISTA PRIMARY KEY (DNI),
	CONSTRAINT FK_EMPLEADO_CONTRATISTA FOREIGN KEY (DNI) REFERENCES PERSONA
);

CREATE EXCEPTION EX_NO_EXCLUYENTES 'Los tipo sub tipo no son mutuamente excluyentes';

SET TERM ^ ;

CREATE TRIGGER TRG_BIEMPLEADO FOR EMPLEADO
ACTIVE
BEFORE INSERT
POSITION 0
AS
BEGIN
	IF ( EXISTS (SELECT * FROM CONTRATISTA WHERE DNI = NEW.DNI) ) THEN
		EXCEPTION EX_NO_EXCLUYENTES;
END^

CREATE TRIGGER TRG_BICONTRATISTA FOR CONTRATISTA
ACTIVE
BEFORE INSERT
POSITION 0
AS
BEGIN
	IF ( EXISTS(SELECT * FROM EMPLEADO WHERE DNI = NEW.DNI) ) THEN
		EXCEPTION EX_NO_EXCLUYENTES;
END^

CREATE TRIGGER TRG_BUEMPLEADO FOR EMPLEADO
ACTIVE
BEFORE UPDATE
POSITION 0
AS
BEGIN
	IF ( EXISTS(SELECT * FROM CONTRATISTA WHERE DNI = NEW.DNI) ) THEN
		EXCEPTION EX_NO_EXCLUYENTES;
END^

CREATE TRIGGER TRG_BUCONTRATISTA FOR CONTRATISTA
ACTIVE
BEFORE UPDATE
POSITION 0
AS
BEGIN
	IF ( EXISTS(SELECT * FROM EMPLEADO WHERE DNI = NEW.DNI) ) THEN
		EXCEPTION EX_NO_EXCLUYENTES;
END^

SET TERM ; ^
