CREATE TABLE CLIENTE(
   ID INTEGER NOT NULL,
   DESCRIPCION VARCHAR(100),

   CONSTRAINT PK_CLIENTE PRIMARY KEY (ID)    
);

CREATE TABLE FACTURA(
   NRO INTEGER NOT NULL,
   DESCRIPCION VARCHAR(100),
   ID INTEGER NOT NULL,

   CONSTRAINT PK_FACTURA PRIMARY KEY (NRO),
   CONSTRAINT FK_FACTURA_CLIENTE FOREIGN KEY (ID) REFERENCES CLIENTE (ID)
);

CREATE TABLE ULTIMAS_VENTAS(
   ID INTEGER NOT NULL,
   NRO INTEGER NOT NULL,
   
   CONSTRAINT PK_ULTIMAS_VENTAS PRIMARY KEY (ID,NRO)
);

SET TERM ^ ;

CREATE TRIGGER TRG_AIFACTURA FOR FACTURA
ACTIVE
AFTER INSERT
POSITION 0
AS
   DECLARE CANTIDAD_VENTAS INTEGER;
   DECLARE VENTA_MAS_ANTIGUA INTEGER;
BEGIN
   INSERT INTO ULTIMAS_VENTAS(ID,NRO) VALUES(NEW.ID,NEW.NRO);
   CANTIDAD_VENTAS = (SELECT COUNT(*) FROM ULTIMAS_VENTAS WHERE ID = NEW.ID);
   IF( CANTIDAD_VENTAS = 4 ) THEN
   BEGIN
      VENTA_MAS_ANTIGUA = (SELECT MIN(NRO) FROM ULTIMAS_VENTAS WHERE ID = NEW.ID);
      DELETE FROM ULTIMAS_VENTAS WHERE NRO = :VENTA_MAS_ANTIGUA;
   END   
END^

CREATE TRIGGER TRG_ADFACTURA FOR FACTURA
ACTIVE
AFTER DELETE
POSITION 0
AS
   DECLARE ID INTEGER;
   DECLARE NRO INTEGER;
BEGIN
   DELETE FROM ULTIMAS_VENTAS WHERE NRO = OLD.NRO;
END^

SET TERM ; ^
