SET TERM ^ ;
   CREATE PROCEDURE SP_EXECUTE_PROCEDURE_1
   (
      FECHA_DESDE TYPE OF COLUMN FACTURA.FECHA,
      FECHA_HASTA TYPE OF COLUMN FACTURA.FECHA
   )
   AS
   BEGIN
      DELETE FROM FACTURA F
      WHERE F.FECHA >= :FECHA_DESDE AND F.FECHA <= :FECHA_HASTA AND F.ESTADO = 2;
   END^

   CREATE PROCEDURE SP_EXECUTE_PROCEDURE_2
   (
      ACCION CHAR(1),
      ID TYPE OF COLUMN PRODUCTO.ID,
      DESCR TYPE OF COLUMN PRODUCTO.DESCR,
      STOCK TYPE OF COLUMN PRODUCTO.STOCK
   )
   RETURNS
   (
      ERROR_CODE INTEGER
   )
   AS
   BEGIN
      ERROR_CODE = 0;
      IF ( ACCION = 'A' ) THEN
         INSERT INTO PRODUCTO(ID,DESCR,STOCK,PRECIO_BASE,PRECIO_COSTO) VALUES (:ID,:DESCR,:STOCK,0,0);
      IF ( ACCION = 'B' ) THEN
         DELETE FROM PRODUCTO WHERE ID = :ID;
      IF ( ACCION = 'C' ) THEN
         UPDATE PRODUCTO SET DESCR = :DESCR,STOCK = :STOCK WHERE ID = :ID;
      WHEN ANY DO
         ERROR_CODE = SQLSTATE;
   END^
   
   CREATE PROCEDURE SP_EXECUTE_PROCEDURE_3
   (
      CANTIDAD INTEGER,
      FECHA_DESDE DATE
   )
   AS
      DECLARE ULTIMO_NRO INTEGER;
   BEGIN
      IF ( CANTIDAD > 0 ) THEN
      BEGIN
         IF ( ( SELECT MAX(NRO) FROM FACTURA ) IS NULL ) THEN
            ULTIMO_NRO = 1;
         ELSE
            ULTIMO_NRO = ( SELECT MAX(NRO) FROM FACTURA ) + 1;
         INSERT INTO FACTURA(NRO,FECHA) VALUES (:ULTIMO_NRO,:FECHA_DESDE);
         EXECUTE PROCEDURE SP_EXECUTE_PROCEDURE_3(:CANTIDAD-1,DATEADD(1 DAY to :FECHA_DESDE));
      END
   END^
SET TERM ; ^
