-- TESTING

-- #### SI AGREGO UN DETALLE, EL SUBTOTAL DEBERIA SER CANTIDAD * PRECIO

-- ## TUPLAS NECESARIAS

EXECUTE PROCEDURE SP_PRODUCTO( 'I',1,'A',5,10,10); --DEBERIA PODER, COMITEAR

EXECUTE PROCEDURE SP_FACTURA('I',1,CURRENT_DATE); --DEBERIA PODER, COMITEAR

-- ##

-- ANTES MIRAR EL IMPORTE DE LA FACTURA Y EL STOCK DE PRODUCTO
EXECUTE PROCEDURE SP_DETALLE('I',1,1,2,10); --DEBERIA PODER, COMITEAR
-- MIRAR EL IMPORTE DE LA FACTURA, DEBERIA SER 20 Y EL STOCK DE PRODUCTO DEBERIA SER 3

-- ## DEJAR LA BASE INTACTA

DELETE FROM DETALLE WHERE NRO > 0;

DELETE FROM PRODUCTO WHERE ID > 0;

DELETE FROM FACTURA WHERE NRO > 0;



-- #### SI MODIFICO LA CANTIDAD DE UN DETALLE PARA ARRIBA, DEBERIA TIRAR ERROR SI ES MAYOR QUE EL STOCK DISPONIBLE
-- #### SI LA MODIFICO PARA ABAJO DEBERIA SUMAR AL STOCK DEL PRODUCTO

-- ## TUPLAS NECESARIAS

EXECUTE PROCEDURE SP_PRODUCTO('I',1,'A',5,10,10); --DEBERIA PODER, COMITEAR

EXECUTE PROCEDURE SP_FACTURA('I',1,CURRENT_DATE); --DEBERIA PODER, COMITEAR

EXECUTE PROCEDURE SP_DETALLE('I',1,1,2,10); --DEBERIA PODER, COMITEAR

-- ##

EXECUTE PROCEDURE SP_DETALLE('U',1,1,1,10); --DEBERIA PODER, NO COMITEAR

EXECUTE PROCEDURE SP_DETALLE('U',1,1,3,10); --DEBERIA PODER, NO COMITEAR

EXECUTE PROCEDURE SP_DETALLE('U',1,1,6,10); --NO DEBERIA PODER, NO COMITEAR

--ANTES MIRAR EL IMPORTE DE LA FATURA Y STOCK DEL PRODUCTO
EXECUTE PROCEDURE SP_DETALLE('U',1,1,3,10); --DEBERIA PODER, COMITEAR
--MIRAR SI EL IMPORTE DE LA FACTURA ES 30, Y SI EL STOCK DE PRODUCTO ES 2

--ANTES MIRAR EL IMPORTE DE LA FATURA
EXECUTE PROCEDURE SP_DETALLE('U',1,1,1,10); --DEBERIA PODER, COMITEAR
--MIRAR SI EL IMPORTE DE LA FACTURA ES 10, Y SI EL STOCK DE PRODUCTO ES 4

-- ## DEJAR LA BASE INTACTA

DELETE FROM DETALLE WHERE NRO > 0;

DELETE FROM PRODUCTO WHERE ID > 0;

DELETE FROM FACTURA WHERE NRO > 0;



-- #### SI AGREGO UN DETALLE, EL SUBTOTAL DEBERIA SUMARSE A LA FACTURA

-- ## TUPLAS NECESARIAS

EXECUTE PROCEDURE SP_PRODUCTO('I',1,'A',1,10,10); --DEBERIA PODER,COMITEAR.

EXECUTE PROCEDURE SP_FACTURA('I',1,CURRENT_DATE); --DEBERIA PODER, COMITEAR

-- ##

EXECUTE PROCEDURE SP_DETALLE('I',1,1,1,10); --DEBERIA PODER,COMITEAR.
--EL IMPORTE DE LA FACTURA DEBERIA SER 10, EL STOCK DEL PRODUCTO 1 DEBERIA SER 0.

-- ## DEJAR LA BASE INTACTA

DELETE FROM DETALLE WHERE NRO > 0;

DELETE FROM PRODUCTO WHERE ID > 0;

DELETE FROM FACTURA WHERE NRO > 0;



-- #### SI ELIMINO UN DETALLE, EL SUBTOTAL DEBERIA RESTARSE A LA FACTURA.

-- ## TUPLAS NECESARIAS

 EXECUTE PROCEDURE SP_PRODUCTO('I',1,'A',1,10,10); --DEBERIA PODER,COMITEAR.

 EXECUTE PROCEDURE SP_PRODUCTO('I',2,'B',1,10,10); --DEBERIA PODER,COMITEAR.

 EXECUTE PROCEDURE SP_FACTURA('I',1,CURRENT_DATE); --DEBERIA PODER,COMITEAR.

 EXECUTE PROCEDURE SP_DETALLE('I',1,1,1,10); --DEBERIA PODER,COMITEAR.

 EXECUTE PROCEDURE SP_DETALLE('I',1,2,1,10); --DEBERIA PODER,COMITEAR.

-- ##

EXECUTE PROCEDURE SP_DETALLE('D',1,2,1,10); --DEBERIA PODER, COMITEAR.
-- EL IMPORTE DE LA FACTURA DEBERIA SER 10, EL STOCK DEL PRODUCTO 2 DEBERIA SER 1 Y EL DEL PRODUCTO 1, 0.

-- ## DEJAR LA BASE INTACTA

DELETE FROM DETALLE WHERE NRO > 0;

DELETE FROM PRODUCTO WHERE ID > 0;

DELETE FROM FACTURA WHERE NRO > 0;




-- #### SI MODIFICO EL PRECIO O CANTIDAD DE UN DETALLE, DEBERIA SUMARSE O RESTARSE CORRECTAMENTE LA FACTURA.

-- ## TUPLAS NECESARIAS

EXECUTE PROCEDURE SP_PRODUCTO('I',1,'A',3,1,1); --DEBERIA PODER,COMITEAR.

EXECUTE PROCEDURE SP_PRODUCTO('I',2,'B',3,1,1); --DEBERIA PODER,COMITEAR.

EXECUTE PROCEDURE SP_FACTURA('I',1,CURRENT_DATE); --DEBERIA PODER,COMITEAR.

EXECUTE PROCEDURE SP_DETALLE('I',1,1,2,10); --DEBERIA PODER,COMITEAR.

EXECUTE PROCEDURE SP_DETALLE('I',1,2,2,10); --DEBERIA PODER,COMITEAR.

-- ##

EXECUTE PROCEDURE SP_DETALLE('U',1,2,3,10); --DEBERIA PODER,COMITEAR.
-- EL IMPORTE DE LA FACTURA DEBERIA SER 50

EXECUTE PROCEDURE SP_DETALLE('U',1,2,1,10); --DEBERIA PODER,COMITEAR.
-- EL IMPORTE DE LA FACTURA DEBERIA SER 30

EXECUTE PROCEDURE SP_DETALLE('U',1,2,1,15); --DEBERIA PODER,COMITEAR.
-- EL IMPORTE DE LA FACTURA DEBERIA SER 35

EXECUTE PROCEDURE SP_DETALLE('U',1,2,1,5); --DEBERIA PODER,COMITEAR.
-- EL IMPORTE DE LA FACTURA DEBERIA SER 25

-- ## DEJAR LA BASE INTACTA

DELETE FROM DETALLE WHERE NRO > 0;

DELETE FROM PRODUCTO WHERE ID > 0;

DELETE FROM FACTURA WHERE NRO > 0;



-- #### SI MODIFICO UN DETALLE, EL SUBOTAL DEBERIA SER CANTIDAD * PRECIO HASTA ACA TESTEE A MANO

-- ## TUPLAS NECESARIAS

 EXECUTE PROCEDURE SP_FACTURA('I',1,CURRENT_DATE);

 EXECUTE PROCEDURE SP_PRODUCTO('I',1,'A',3,1,1); --DEBERIA PODER,COMITEAR.

 EXECUTE PROCEDURE SP_DETALLE('I',1,1,1,10); --DEBERIA PODER,COMITEAR.

-- ##

 EXECUTE PROCEDURE SP_DETALLE('U',1,1,1,15); -- DEBERIA PODER, COMITEAR.
-- EL SUBTOTAL DEL DETALLE DEBERIA SER 15

 EXECUTE PROCEDURE SP_DETALLE('U',1,1,2,15); -- DEBERIA PODER, COMITEAR.
-- EL SUBTOTAL DEL DETALLE DEBERIA SER 30

-- ## DEJAR LA BASE INTACTA

DELETE FROM DETALLE WHERE NRO > 0;

DELETE FROM PRODUCTO WHERE ID > 0;

DELETE FROM FACTURA WHERE NRO > 0;



-- #### SI INGRESO O MODIFICO UN DETALLE CON PRECIO MENOR AL PRECIO_BASE DEL PRODUCTO, NO DEBERIA ANDAR.

-- ## TUPLAS NECESARIAS

 EXECUTE PROCEDURE SP_PRODUCTO ('I',1,'A',1,10,10); --DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_FACTURA ('I',1,CURRENT_DATE);

-- ##

 EXECUTE PROCEDURE SP_DETALLE ('I',1,1,1,9); --NO DEBERIA PODER

 EXECUTE PROCEDURE SP_DETALLE ('I',1,1,1,10); --DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_DETALLE ('U',1,1,1,9); --NO DEBERIA PODER

 EXECUTE PROCEDURE SP_DETALLE ('U',1,1,1,15); --DEBERIA PODER, COMITEAR.

-- ## DEJAR LA BASE INTACTA

DELETE FROM DETALLE WHERE NRO > 0;

DELETE FROM PRODUCTO WHERE ID > 0;

DELETE FROM FACTURA WHERE NRO > 0;



-- #### VERIFICAR LAS TRANSISIONES DE ESTADOS

-- ## TUPLAS NECESARIAS

 EXECUTE PROCEDURE SP_FACTURA ('I',1,CURRENT_DATE); --DEBERIA PODER, COMITEAR.

-- ##

 EXECUTE PROCEDURE SP_ESTADO_FACTURA(1,1); --DEBERIA PODER, NO COMITEAR.

 EXECUTE PROCEDURE SP_ESTADO_FACTURA(2,1); --DEBERIA PODER, NO COMITEAR.

 EXECUTE PROCEDURE SP_ESTADO_FACTURA(1,1); --DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_ESTADO_FACTURA(0,1); --NO DEBERIA PODER, NO COMITEAR.

 EXECUTE PROCEDURE SP_ESTADO_FACTURA(2,1); --DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_ESTADO_FACTURA(0,1); --NO DEBERIA PODER, NO COMITEAR.

-- ## DEJAR LA BASE INTACTA

DELETE FROM DETALLE WHERE NRO > 0;

DELETE FROM PRODUCTO WHERE ID > 0;

DELETE FROM FACTURA WHERE NRO > 0;



-- #### SI PASO UNA FACTURA DE FINALIZADA A ANULADA DEBERIA DEVOLVER LOS PRODUCTOS AL STOCK

-- ## TUPLAS NECESARIAS

 EXECUTE PROCEDURE SP_PRODUCTO('I',1,'A',1,10,10); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_PRODUCTO('I',2,'B',1,10,10); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_FACTURA('I',1,CURRENT_DATE); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_DETALLE('I',1,1,1,10); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_DETALLE('I',1,2,1,10); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_ESTADO_FACTURA(1,1); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_FACTURA('I',2,CURRENT_DATE); -- DEBERIA PODER, COMITEAR.


-- ##

 EXECUTE PROCEDURE SP_ESTADO_FACTURA(2,1); -- DEBERIA PODER, COMITEAR.
-- VERIFICAR SI SE LE SUMO STOCK A LOS PRODUCTOS

-- SI PASO UNA FACTURA DE ANULADA A FINALIZADA DEBERIA RESTAR LOS PRODUCTOS DEL STOCK

 EXECUTE PROCEDURE SP_ESTADO_FACTURA(1,1); -- DEBERIA PODER, COMITEAR.
-- VERIFICAR SI SE LE RESTÓ STOCK A LOS PRODUCTOS

-- ## SI NO HAY STOCK PARA RESTAR A LOS PRODUCTOS, NO DEBERIA PODER PASAR A FINALIZADA.

 EXECUTE PROCEDURE SP_ESTADO_FACTURA(2,1); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_DETALLE('I',2,1,1,10); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_ESTADO_FACTURA(1,1); -- NO DEBERIA PODER, COMITEAR.
-- VERIFICAR SI SE LE RESTÓ STOCK A LOS PRODUCTOS Y EN QUE ESTADO ESTA LA FACTURA

 EXECUTE PROCEDURE SP_DETALLE('D',2,1,1,10); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_ESTADO_FACTURA(1,1); -- DEBERIA PODER, COMITEAR.
-- VERIFICAR SI SE LE RESTÓ STOCK A LOS PRODUCTOS Y EN QUE ESTADO ESTA LA FACTURA


-- ## DEJAR LA BASE INTACTA

DELETE FROM DETALLE WHERE NRO > 0;

DELETE FROM PRODUCTO WHERE ID > 0;

DELETE FROM FACTURA WHERE NRO > 0;



-- #### SI INGRESO UNA FACTURA CON UNA FECHA MENOR A LA MAXIMA, NO ME DEBERIA DEJAR

 EXECUTE PROCEDURE SP_FACTURA('I',1,'10.10.2020'); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_FACTURA('I',2,'10.10.2020'); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_FACTURA('I',3,'9.10.2020'); -- NO DEBERIA PODER

 EXECUTE PROCEDURE SP_FACTURA('I',4,'11.10.2020'); -- DEBERIA PODER, COMITEAR

-- ## DEJAR LA BASE INTACTA

DELETE FROM DETALLE WHERE NRO > 0;

DELETE FROM PRODUCTO WHERE ID > 0;

DELETE FROM FACTURA WHERE NRO > 0;



-- #### TESTING SELECT PROCEDURE 1 Y 2

-- ## TUPLAS NECESARIAS

 EXECUTE PROCEDURE SP_PRODUCTO('I',1,'A',10,1,1);

 EXECUTE PROCEDURE SP_FACTURA('I',1,CURRENT_DATE);

 EXECUTE PROCEDURE SP_DETALLE('I',1,1,1,1);

 EXECUTE PROCEDURE SP_FACTURA('I',2,CURRENT_DATE);

 EXECUTE PROCEDURE SP_DETALLE('I',2,1,1,2);

 EXECUTE PROCEDURE SP_FACTURA('I',3,CURRENT_DATE);

 EXECUTE PROCEDURE SP_DETALLE('I',3,1,1,3);

 EXECUTE PROCEDURE SP_FACTURA('I',4,CURRENT_DATE);

 EXECUTE PROCEDURE SP_DETALLE('I',4,1,1,4);

 EXECUTE PROCEDURE SP_FACTURA('I',5,CURRENT_DATE);

 EXECUTE PROCEDURE SP_DETALLE('I',5,1,1,5);

 EXECUTE PROCEDURE SP_FACTURA('I',6,CURRENT_DATE);

 EXECUTE PROCEDURE SP_DETALLE('I',6,1,1,6);

-- ##

 SELECT * FROM SP_SELECT_PROCEDURE_1Y2(2,5); --DEBERIA PODER, COMITEAR.
-- DEBERIA DEVOLVER LAS FACTURAS CON IMPORTE 2,3,4 Y 5.

 SELECT * FROM SP_SELECT_PROCEDURE_1Y2(NULL,5);
-- DEBERIA DEVOLVER LAS FACTURAS CON IMPORTE 1,2,3,4 Y 5.

 SELECT * FROM SP_SELECT_PROCEDURE_1Y2(3,NULL);
-- DEBERIA DEVOLVER LAS FACTURAS CON IMPORTE 3,4,5 Y 6.

 SELECT * FROM SP_SELECT_PROCEDURE_1Y2(NULL,NULL);
-- DEBERIA DEVOLVER LAS FACTURAS CON IMPORTE 1,2,3,4,5 y 6. (TODAS)

-- ## DEJAR LA BASE INTACTA

DELETE FROM DETALLE WHERE NRO > 0;

DELETE FROM PRODUCTO WHERE ID > 0;

DELETE FROM FACTURA WHERE NRO > 0;



-- ## TESTING SELECT PROCEDURE 3

-- ## TUPLAS NECESARIAS

 EXECUTE PROCEDURE SP_PRODUCTO ('I',1,'A',10,1,1); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_PRODUCTO ('I',2,'B',10,1,1); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_PRODUCTO ('I',3,'C',10,1,1); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_PRODUCTO ('I',4,'D',10,1,1); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_PRODUCTO ('I',5,'E',10,1,1); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_PRODUCTO ('I',6,'F',10,1,1); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_FACTURA ('I',1,CURRENT_DATE); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_FACTURA ('I',2,CURRENT_DATE); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_FACTURA ('I',3,CURRENT_DATE); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_FACTURA ('I',4,CURRENT_DATE); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_FACTURA ('I',5,CURRENT_DATE); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_FACTURA ('I',6,CURRENT_DATE); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_FACTURA ('I',7,CURRENT_DATE); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_DETALLE ('I',1,1,2,2); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_DETALLE ('I',2,3,1,2); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_DETALLE ('I',3,5,1,8); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_DETALLE ('I',4,6,2,6); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_DETALLE ('I',5,6,3,6); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_DETALLE ('I',6,2,5,9); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_DETALLE ('I',7,4,6,7); -- DEBERIA PODER, COMITEAR.

-- ##

 SELECT * FROM SP_SELECT_PROCEDURE_3(3,6);

-- DEBERIA DEVOLVER: ID 2, TOTAL 45, CANTIDAD 5 
--                   ID 5, TOTAL 8, CANTIDAD 1 
--                   ID 6, TOTAL 30, CANTIDAD 5 

-- ## DEJAR LA BASE INTACTA

DELETE FROM DETALLE WHERE NRO > 0;

DELETE FROM PRODUCTO WHERE ID > 0;

DELETE FROM FACTURA WHERE NRO > 0;



-- #### TESTING SELECT PROCEDURE 4

-- ## TUPLAS NECESARIAS

 EXECUTE PROCEDURE SP_PRODUCTO ('I',1,'A',10,1,1); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_PRODUCTO ('I',2,'B',10,1,1); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_PRODUCTO ('I',3,'C',10,1,1); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_PRODUCTO ('I',4,'D',10,1,1); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_PRODUCTO ('I',5,'E',10,1,1); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_PRODUCTO ('I',6,'F',10,1,1); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_PRODUCTO ('I',7,'G',10,1,1); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_FACTURA ('I',1,CURRENT_DATE); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_FACTURA ('I',2,CURRENT_DATE); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_FACTURA ('I',3,CURRENT_DATE); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_FACTURA ('I',4,CURRENT_DATE); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_FACTURA ('I',5,CURRENT_DATE); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_FACTURA ('I',6,CURRENT_DATE); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_FACTURA ('I',7,CURRENT_DATE); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_DETALLE ('I',1,1,2,2); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_DETALLE ('I',2,3,1,2); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_DETALLE ('I',3,5,1,8); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_DETALLE ('I',4,6,2,6); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_DETALLE ('I',5,6,3,6); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_DETALLE ('I',6,2,5,9); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_DETALLE ('I',7,4,6,7); -- DEBERIA PODER, COMITEAR.

-- ##

 SELECT * FROM SP_SELECT_PROCEDURE_4;

-- DEBERIA DEVOLVER: 1 A 8 1
--                   2 B 5 6
--                   3 C 9 2
--                   4 D 4 7
--                   5 E 9 3
--                   6 F 5 5 4
--                   7 G 10

-- ## DEJAR LA BASE INTACTA

DELETE FROM DETALLE WHERE NRO > 0;

DELETE FROM PRODUCTO WHERE ID > 0;

DELETE FROM FACTURA WHERE NRO > 0;



-- #### TESTING SELECT PROCEDURE 5

-- ##

 EXECUTE PROCEDURE SP_FACTURA('I',1,CURRENT_DATE);

 EXECUTE PROCEDURE SP_FACTURA('I',2,CURRENT_DATE);

 EXECUTE PROCEDURE SP_FACTURA('I',3,CURRENT_DATE);

 EXECUTE PROCEDURE SP_FACTURA('I',4,CURRENT_DATE);

 EXECUTE PROCEDURE SP_FACTURA('I',5,CURRENT_DATE);

 EXECUTE PROCEDURE SP_FACTURA('I',6,CURRENT_DATE);

 EXECUTE PROCEDURE SP_FACTURA('I',7,CURRENT_DATE);

 EXECUTE PROCEDURE SP_FACTURA('I',8,CURRENT_DATE);

 EXECUTE PROCEDURE SP_FACTURA('I',9,CURRENT_DATE);

 EXECUTE PROCEDURE SP_FACTURA('I',10,CURRENT_DATE);

 EXECUTE PROCEDURE SP_PRODUCTO('I',1,'A',10,10,10);

 EXECUTE PROCEDURE SP_PRODUCTO('I',2,'A',10,100,100);

 EXECUTE PROCEDURE SP_PRODUCTO('I',3,'A',10,1000,1000);

 EXECUTE PROCEDURE SP_PRODUCTO('I',4,'A',10,10000,10000);

 EXECUTE PROCEDURE SP_PRODUCTO('I',5,'A',10,100000,100000);

 EXECUTE PROCEDURE SP_PRODUCTO('I',6,'A',10,123,123);

 EXECUTE PROCEDURE SP_PRODUCTO('I',7,'A',10,123123,123123);

 EXECUTE PROCEDURE SP_DETALLE('I',1,1,3,10);

 EXECUTE PROCEDURE SP_DETALLE('I',2,2,1,100);

 EXECUTE PROCEDURE SP_DETALLE('I',3,3,3,1000);

 EXECUTE PROCEDURE SP_DETALLE('I',4,4,4,10000);

 EXECUTE PROCEDURE SP_DETALLE('I',5,5,6,1000000);

 EXECUTE PROCEDURE SP_DETALLE('I',6,6,10,123);

 EXECUTE PROCEDURE SP_DETALLE('I',7,7,1,123123);

 EXECUTE PROCEDURE SP_DETALLE('I',8,2,3,100);

-- ##

 SELECT * FROM SP_SELECT_PROCEDURE_5;

-- DEBERIA DEVOLVER: FAC100 = 4
--                   FAC1000 = 1
--                   FAC10000 = 2
--                   FAC100000 = 1

-- ## DEJAR LA BASE INTACTA

DELETE FROM DETALLE WHERE NRO > 0;

DELETE FROM PRODUCTO WHERE ID > 0;

DELETE FROM FACTURA WHERE NRO > 0;



-- #### TESTING SELECT PROCEDURE 6

 EXECUTE PROCEDURE SP_FACTURA('I',1,CURRENT_DATE);

 EXECUTE PROCEDURE SP_FACTURA('I',2,CURRENT_DATE);

 EXECUTE PROCEDURE SP_FACTURA('I',3,CURRENT_DATE);

 EXECUTE PROCEDURE SP_FACTURA('I',4,CURRENT_DATE);

 EXECUTE PROCEDURE SP_FACTURA('I',5,CURRENT_DATE);

 EXECUTE PROCEDURE SP_FACTURA('I',6,CURRENT_DATE);

 EXECUTE PROCEDURE SP_FACTURA('I',7,CURRENT_DATE);

 EXECUTE PROCEDURE SP_FACTURA('I',8,CURRENT_DATE);

 EXECUTE PROCEDURE SP_FACTURA('I',9,CURRENT_DATE);

 EXECUTE PROCEDURE SP_PRODUCTO('I',1,'A',1002,10,10); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_PRODUCTO('I',2,'B',1002,10,10); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_PRODUCTO('I',3,'C',1002,10,10); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_PRODUCTO('I',4,'D',1002,10,10); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_PRODUCTO('I',5,'E',1002,10,10); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_PRODUCTO('I',6,'F',1002,10,10); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_PRODUCTO('I',7,'G',1002,10,10); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_PRODUCTO('I',8,'H',1002,10,10); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_PRODUCTO('I',9,'I',1002,10,10); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_PRODUCTO('I',10,'J',1002,10,10); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_PRODUCTO('I',11,'K',1002,10,10); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_PRODUCTO('I',12,'X',1002,10,10); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_PRODUCTO('I',13,'Y',1002,10,10); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_PRODUCTO('I',14,'Z',1002,10,10); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_PRODUCTO('I',15,'AA',1002,10,10); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_PRODUCTO('I',16,'BB',1002,10,10); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_PRODUCTO('I',17,'CC',1002,10,10); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_DETALLE('I',1,1,1,10); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_DETALLE('I',2,2,2,10); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_DETALLE('I',3,3,3,10); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_DETALLE('I',4,4,4,10); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_DETALLE('I',5,5,1,10); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_DETALLE('I',6,6,2,10); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_DETALLE('I',7,7,3,10); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_DETALLE('I',8,8,4,10); -- DEBERIA PODER, COMITEAR.

-- A PARTIR DE ACA SON LOS SEGUNDOS PRODUCTOS

 EXECUTE PROCEDURE SP_DETALLE('I',1,9,1,10); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_DETALLE('I',2,10,2,10); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_DETALLE('I',3,11,3,10); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_DETALLE('I',4,12,4,10); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_DETALLE('I',5,13,1,10); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_DETALLE('I',6,14,2,10); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_DETALLE('I',7,15,3,10); -- DEBERIA PODER, COMITEAR.

 EXECUTE PROCEDURE SP_DETALLE('I',8,16,4,10); -- DEBERIA PODER, COMITEAR.

-- ESTA ES UNA FACTURA CON UN SOLO PRODUCTO CON MENOS DE 1000 DE STOCK

 EXECUTE PROCEDURE SP_DETALLE('I',9,17,4,10); -- DEBERIA PODER, COMITEAR.

-- ##

 SELECT * FROM SP_SELECT_PROCEDURE_6
-- DEBERIA DEVOLVER LAS FACTURAS CON NRO: 3, 4, 7, 8.

-- ## DEJAR LA BASE INTACTA

DELETE FROM DETALLE WHERE NRO > 0;

DELETE FROM PRODUCTO WHERE ID > 0;

DELETE FROM FACTURA WHERE NRO > 0;



-- #### TESTING SELECT PROCEDURE 7

-- ## TUPLAS NECESARIAS

EXECUTE PROCEDURE SP_PRODUCTO('I',1,'A',800,1,1);

EXECUTE PROCEDURE SP_FACTURA('I',1,'15.01.2010');

EXECUTE PROCEDURE SP_DETALLE('I',1,1,5,8);

EXECUTE PROCEDURE SP_FACTURA('I',2,'15.01.2010');

EXECUTE PROCEDURE SP_DETALLE('I',2,1,3,2);

EXECUTE PROCEDURE SP_FACTURA('I',3,'15.03.2010');

EXECUTE PROCEDURE SP_DETALLE('I',3,1,7,8);

EXECUTE PROCEDURE SP_FACTURA('I',4,'15.03.2010');

EXECUTE PROCEDURE SP_DETALLE('I',4,1,2,4);

EXECUTE PROCEDURE SP_FACTURA('I',5,'15.04.2010');

EXECUTE PROCEDURE SP_DETALLE('I',5,1,7,9);

EXECUTE PROCEDURE SP_FACTURA('I',6,'15.05.2010');

EXECUTE PROCEDURE SP_DETALLE('I',6,1,4,4);

EXECUTE PROCEDURE SP_FACTURA('I',7,'15.05.2010');

EXECUTE PROCEDURE SP_DETALLE('I',7,1,8,8);

EXECUTE PROCEDURE SP_FACTURA('I',8,'15.06.2010');

EXECUTE PROCEDURE SP_DETALLE('I',8,1,1,2);

EXECUTE PROCEDURE SP_FACTURA('I',9,'15.01.2020');

EXECUTE PROCEDURE SP_DETALLE('I',9,1,5,8);

EXECUTE PROCEDURE SP_FACTURA('I',10,'15.02.2020');

EXECUTE PROCEDURE SP_DETALLE('I',10,1,3,2);

EXECUTE PROCEDURE SP_FACTURA('I',11,'15.04.2020');

EXECUTE PROCEDURE SP_DETALLE('I',11,1,7,8);

EXECUTE PROCEDURE SP_FACTURA('I',12,'15.04.2020');

EXECUTE PROCEDURE SP_DETALLE('I',12,1,2,4);

EXECUTE PROCEDURE SP_FACTURA('I',13,'15.05.2020');

EXECUTE PROCEDURE SP_DETALLE('I',13,1,7,9);

EXECUTE PROCEDURE SP_FACTURA('I',14,'15.06.2020');

EXECUTE PROCEDURE SP_DETALLE('I',14,1,4,4);

EXECUTE PROCEDURE SP_FACTURA('I',15,'15.06.2020');

EXECUTE PROCEDURE SP_DETALLE('I',15,1,8,8);

EXECUTE PROCEDURE SP_FACTURA('I',16,'15.07.2020');

EXECUTE PROCEDURE SP_DETALLE('I',16,1,1,2);

-- ##

SELECT * FROM SP_SELECT_PROCEDURE_7(2020);
-- DEBERIA DEVOLVER 40, 6, null, 64, 63, 80, 2, null, null, null, null, null

SELECT * FROM SP_SELECT_PROCEDURE_7(2010);
-- DEBERIA DEVOLVER 46, null, 64, 63, 80, 2, null, null, null, null, null, null

-- ## DEJAR LA BASE INTACTA

DELETE FROM DETALLE WHERE NRO > 0;

DELETE FROM PRODUCTO WHERE ID > 0;

DELETE FROM FACTURA WHERE NRO > 0;



-- #### TESTING EXECUTE PROCEDURE 1

-- ## TUPLAS NECESARIAS

EXECUTE PROCEDURE SP_FACTURA('I',1,'15.01.2020');

EXECUTE PROCEDURE SP_ESTADO_FACTURA(2,1);

EXECUTE PROCEDURE SP_FACTURA('I',2,'15.02.2020');

EXECUTE PROCEDURE SP_ESTADO_FACTURA(1,2);

EXECUTE PROCEDURE SP_FACTURA('I',3,'15.03.2020');

EXECUTE PROCEDURE SP_ESTADO_FACTURA(2,3);

EXECUTE PROCEDURE SP_FACTURA('I',4,'15.04.2020');

EXECUTE PROCEDURE SP_ESTADO_FACTURA(1,4);

EXECUTE PROCEDURE SP_FACTURA('I',5,'15.05.2020');

EXECUTE PROCEDURE SP_ESTADO_FACTURA(2,5);

EXECUTE PROCEDURE SP_FACTURA('I',6,'15.06.2020');

-- ESTA VA A ESTAR EN ESTADO 0

EXECUTE PROCEDURE SP_FACTURA('I',7,'15.07.2020');

EXECUTE PROCEDURE SP_ESTADO_FACTURA(1,7);

-- ##

EXECUTE PROCEDURE SP_EXECUTE_PROCEDURE_1('15.02.2020','15.06.2020');
-- DEBERIAN QUEDAR LAS FACTURAS 1,2,4,6,7

-- ## DEJAR LA BASE INTACTA

DELETE FROM DETALLE WHERE NRO > 0;

DELETE FROM PRODUCTO WHERE ID > 0;

DELETE FROM FACTURA WHERE NRO > 0;



-- #### TESTING EXECUTE_PROCEDURE_2

EXECUTE PROCEDURE SP_EXECUTE_PROCEDURE_2('A',1,'A',10);
-- DEBERIA INSERTAR EL PRODUCTO 1

EXECUTE PROCEDURE SP_EXECUTE_PROCEDURE_2('C',1,'B',10);
-- DEBERIA CAMBIARLE LA DESCRIPCION AL PRODUCTO 1

EXECUTE PROCEDURE SP_EXECUTE_PROCEDURE_2('B',1,'A',10);
-- DEBERIA ELIMIAR EL PRODUCTO 1




-- #### TESTING EXECUTE_PROCEDURE_3

-- ## TUPLAS NECESARIAS

EXECUTE PROCEDURE SP_FACTURA('I',1,'10.10.1010');

-- ##

EXECUTE PROCEDURE SP_EXECUTE_PROCEDURE_3(5,'5.10.1010'); -- NO DEBERIA PODDER PORQUE LA FECHA ES MENOR A LA FECHA DE LA ULTIMA FACTURA

EXECUTE PROCEDURE SP_EXECUTE_PROCEDURE_3(5,'10.10.1010'); -- DEBERIA PODER, COMITEAR.
-- DEBERIA INSERTAR LAS FACTURAS 2,3,4,5,6 EN LOS DIAS 10,11,12,13,14

DELETE FROM FACTURA WHERE NRO > 0;

EXECUTE PROCEDURE SP_EXECUTE_PROCEDURE_3(5,'5.5.1010'); -- DEBERIA PODER, COMITEAR.
-- DEBERIA INSERTAR LAS FACTURAS 1,2,3,4,5 EN LOS DIAS 5,6,7,8,9

-- ## DEJAR LA BASE INTACTA

DELETE FROM DETALLE WHERE NRO > 0;

DELETE FROM PRODUCTO WHERE ID > 0;

DELETE FROM FACTURA WHERE NRO > 0;
