MODELO A

CREATE TABLE CLIENTE(
	ID_CLIENTE INT NOT NULL,
	NOMBRE VARCHAR(20) NOT NULL,
	
	CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE CLIENTE_AUX(
	ULTIMO_ID INT DEFAULT 0,
	
	CONSTRAINT PK_CLIENTE_AUX PRIMARY KEY (ULTIMO_ID)
);

SET TERM ^ ;

CREATE TRIGGER BI_CLIENTE FOR CLIENTE
ACTIVE
BEFORE INSERT
POSITION 0
AS
	DECLARE ULTIMO_ID_AUX INTEGER;
BEGIN
	ULTIMO_ID_AUX = (SELECT ULTIMO_ID FROM CLIENTE_AUX);
	NEW.ID_CLIENTE = :ULTIMO_ID_AUX;
	UPDATE CLIENTE_AUX SET ULTIMO_ID = ULTIMO_ID + 1 WHERE ULTIMO_ID = :ULTIMO_ID_AUX;
END^

SET TERM ; ^
