CREATE TABLE FACTURA
(
    NRO INTEGER NOT NULL,
    IMPORTE INTEGER NOT NULL,
    
    CONSTRAINT PK_NRO PRIMARY KEY (NRO)
);

CREATE GENERATOR GEN_NRO_FACTURA;
SET GENERATOR GEN_NRO_FACTURA TO 0;

CREATE EXCEPTION EX_NRO_FACTURA 'No se puede modificar el NRO de factura';

SET TERM ^ ;

CREATE TRIGGER TRG_BIFACTURA FOR FACTURA 
    ACTIVE 
    BEFORE INSERT
    POSITION 0 
    AS 
BEGIN 
   NEW.NRO = GEN_ID(GEN_NRO_FACTURA,1);
END^

CREATE TRIGGER TRG_BUFACTURA FOR FACTURA
   ACTIVE
   BEFORE UPDATE
   POSITION 0
   AS
BEGIN
   IF (NEW.NRO <> OLD.NRO) THEN
      EXCEPTION EX_NRO_FACTURA;
END^

SET TERM ; ^

-- SEGURIDAD

CREATE USER AGUSTINEJ1
   PASSWORD 'asdasd'
   FIRSTNAME 'Agustin'
   MIDDLENAME ''
   LASTNAME 'Normand';

CREATE ROLE USUARIO;

GRANT SELECT ON FACTURA TO USUARIO;

GRANT UPDATE ON FACTURA TO USUARIO;

GRANT DELETE ON FACTURA TO USUARIO;

GRANT INSERT ON FACTURA TO USUARIO;

-- NO ES NECESARIO GARANTIZAR PERMIZOS A EXCEPCIONES Y GENERATORS

--GRANT USAGE ON SEQUENCE GENERATOR GEN_NRO_FACTURA TO TRIGGER TRG_BIFACTURA;

--GRANT USAGE ON EXCEPTION EX_NRO_FACTURA TO TRIGGER TRG_BUFACTURA;

GRANT USUARIO TO AGUSTINEJ1;
