-- TESTING

INSERT INTO FACTURA (IMPORTE)
VALUES (100);

-- NO DEBERIA TIRAR ERROR POR TENER UN ATRIBUTO MENOS, PORQUE EL TRIGGER LO COMPLETA
-- DEBERIA TENER EL NRO 1.

INSERT INTO FACTURA (IMPORTE)
VALUES (200);

DELETE FROM FACTURA
WHERE NRO = 1;

DELETE FROM FACTURA
WHERE NRO = 2;

INSERT INTO FACTURA (IMPORTE)
VALUES (300);

-- LA NUEVA FACTURA DEBERIA TENER ID 3 E IMPORTE 300

UPDATE FACTURA
SET NRO = 1
WHERE NRO = 3;

-- NO DEBERIA DEJARME

UPDATE FACTURA
SET IMPORTE = 500
WHERE NRO = 3;

-- LA FACTURA CON NRO 3 DEBERIA TENER 500 EN EL IMPORTE
