CREATE TABLE PERSONA 
(
    DNI INTEGER NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(20) NOT NULL
);

CREATE TABLE ESTUDIANTE
(
    DNI INTEGER NOT NULL PRIMARY KEY,
    CONSTRAINT FK_ESTUDIANTE_PERSONA FOREIGN KEY (DNI) REFERENCES PERSONA
);

CREATE TABLE DOCENTE
(
    DNI INTEGER NOT NULL PRIMARY KEY,
    CONSTRAINT FK_DOCENTE_PERSONA FOREIGN KEY (DNI) REFERENCES PERSONA
);

CREATE EXCEPTION EX_NO_EXCLUYENTES 'No se puede ser estudiante y docente';

SET TERM ^ ; 

CREATE TRIGGER TRG_BIDOCENTE FOR DOCENTE
    ACTIVE
    BEFORE INSERT
    POSITION 0
AS
BEGIN
    IF ( EXISTS( SELECT * FROM ESTUDIANTE WHERE ESTUDIANTE.DNI = NEW.DNI )) THEN
      EXCEPTION EX_NO_EXCLUYENTES;
END^
    
CREATE TRIGGER TRG_BIESTUDIANTE FOR ESTUDIANTE
    ACTIVE
    BEFORE INSERT
    POSITION 0
AS
BEGIN
    IF ( EXISTS( SELECT * FROM DOCENTE WHERE DOCENTE.DNI = NEW.DNI )) THEN
      EXCEPTION EX_NO_EXCLUYENTES;
END^
    
CREATE TRIGGER TRG_BUDOCENTE FOR DOCENTE
   ACTIVE
   BEFORE UPDATE
   POSITION 0
   AS
BEGIN
   IF (NEW.DNI <> OLD.DNI) THEN
      IF ( EXISTS ( SELECT * FROM ESTUDIANTE WHERE DNI = NEW.DNI) ) THEN
         EXCEPTION EX_NO_EXCLUYENTES;
END^

CREATE TRIGGER TRG_BUESTUDIANTE FOR ESTUDIANTE
   ACTIVE
   BEFORE UPDATE
   POSITION 0
   AS
BEGIN
   IF (NEW.DNI <> OLD.DNI) THEN
      IF ( EXISTS ( SELECT * FROM DOCENTE WHERE DNI = NEW.DNI) ) THEN
         EXCEPTION EX_NO_EXCLUYENTES;
END^

SET TERM ; ^

-- SEGURIDAD

CREATE USER AGUSTINEJ2
   PASSWORD 'asdasd'
   FIRSTNAME 'Agustin'
   MIDDLENAME ''
   LASTNAME 'Normand';

CREATE ROLE USUARIO;

GRANT USUARIO TO AGUSTINEJ2;

GRANT SELECT ON PERSONA TO USUARIO;

GRANT UPDATE ON PERSONA TO USUARIO;

GRANT INSERT ON PERSONA TO USUARIO;

GRANT DELETE ON PERSONA TO USUARIO;

GRANT SELECT ON ESTUDIANTE TO USUARIO;

GRANT UPDATE ON ESTUDIANTE TO USUARIO;

GRANT INSERT ON ESTUDIANTE TO USUARIO;

GRANT DELETE ON ESTUDIANTE TO USUARIO;

GRANT SELECT ON DOCENTE TO USUARIO;

GRANT UPDATE ON DOCENTE TO USUARIO;

GRANT INSERT ON DOCENTE TO USUARIO;

GRANT DELETE ON DOCENTE TO USUARIO;
