CREATE TABLE PERSONA
(
DNI integer NOT NULL primary key,
APENOM varchar(100)
);
CREATE TABLE CONTRATISTA
(
DNI INTEGER NOT NULL PRIMARY KEY,
VALORHORA DOUBLE PRECISION,
CONSTRAINT FK_CONTRATISTA_PER FOREIGN KEY (DNI) REFERENCES PERSONA

);
CREATE TABLE EMPLEADO
(
DNI INTEGER NOT NULL PRIMARY KEY,
SALARIO DOUBLE PRECISION,
CONSTRAINT FK_EMPLEADO_PER FOREIGN KEY (DNI) REFERENCES PERSONA
);

ALTER TABLE CONTRATISTA
ADD CONSTRAINT CH
  CHECK (DNI <> (SELECT e.DNI FROM EMPLEADO e WHERE e.DNI);
  
  ALTER TABLE EMPLEADO
ADD CONSTRAINT CH
  CHECK (DNI <> (SELECT p.DNI FROM PERSONA p WHERE p.DNI);
