CREATE TABLE FACTURA (
	NRO INT NOT NULL,
	DETALLES INT NOT NULL,
	CONSTRAINT PK_FACTURA PRIMARY KEY (NRO)
);

CREATE TABLE DETALLE (
	NRO INT NOT NULL,
	DESCRIPCION VARCHAR(20) NOT NULL,
	CONSTRAINT PK_DETALLE PRIMARY KEY (NRO,DESCRIPCION),
	CONSTRAINT FK_DETALLE FOREIGN KEY (NRO) REFERENCES FACTURA
);

CREATE EXCEPTION EX_MAX_DETALLES 'Ya se alcanzó la cantidad máxima de detalles en la factura';

SET TERM ^ ;

CREATE TRIGGER TRG_BIFACTURA FOR FACTURA
ACTIVE 
BEFORE INSERT
POSITION 0
AS
BEGIN
	NEW.DETALLES = 0;
END^

CREATE TRIGGER TRG_BIDETALLE FOR DETALLE
ACTIVE 
BEFORE INSERT
POSITION 0
AS
BEGIN
	IF ((SELECT DETALLES FROM FACTURA WHERE NRO = NEW.NRO) = 3) THEN
		EXCEPTION EX_MAX_DETALLES;
END^

CREATE TRIGGER TRG_AIDETALLE FOR DETALLE
ACTIVE 
AFTER INSERT
POSITION 0
AS
BEGIN
	UPDATE FACTURA SET DETALLES = DETALLES + 1 WHERE NRO = NEW.NRO;
END^

CREATE TRIGGER TRG_BUDETALLE FOR DETALLE
ACTIVE 
BEFORE UPDATE
POSITION 0
AS
BEGIN
	IF (OLD.NRO <> NEW.NRO) THEN
		IF ((SELECT DETALLES FROM FACTURA WHERE NRO = NEW.NRO) = 3) THEN
			EXCEPTION EX_MAX_DETALLES;
END^

CREATE TRIGGER TRG_AUDETALLE FOR DETALLE
ACTIVE 
AFTER UPDATE
POSITION 0
AS
BEGIN
	IF (OLD.NRO <> NEW.NRO) THEN
	BEGIN
		UPDATE FACTURA SET DETALLES = DETALLES + 1 WHERE NRO = NEW.NRO;
		UPDATE FACTURA SET DETALLES = DETALLES - 1 WHERE NRO = OLD.NRO;
	END
END^

CREATE TRIGGER TRG_ADDETALLE FOR DETALLE
ACTIVE 
AFTER DELETE
POSITION 0
AS
BEGIN
	UPDATE FACTURA SET DETALLES = DETALLES - 1 WHERE NRO = OLD.NRO;
END^

SET TERM ; ^
