CREATE TABLE FACTURA(
	NRO INT NOT NULL,
	CONSTRAINT PK_FACTURA PRIMARY KEY (NRO)
);

CREATE TABLE FACTURA_AUX(
	NRO INT NOT NULL,
	DETALLES INT NOT NULL,
	CONSTRAINT PK_FACTURA_AUX PRIMARY KEY (NRO),
	CONSTRAINT FK_FACTURA_AUX_FACTURA FOREIGN KEY (NRO) REFERENCES FACTURA
);

CREATE TABLE DETALLE(
	NRO INT NOT NULL,
	DESCR VARCHAR(20) NOT NULL,
	CONSTRAINT PK_DETALLE PRIMARY KEY (NRO,DESCR),
	CONSTRAINT FK_DETALLE_FACTURA FOREIGN KEY (NRO) REFERENCES FACTURA
);

CREATE EXCEPTION EX_MAX_DETALLES 'Cantidad máxima de detalles';

SET TERM ^ ;

CREATE TRIGGER TRG_AIFACTURA FOR FACTURA
ACTIVE
AFTER INSERT
POSITION 0
AS
BEGIN
 INSERT INTO FACTURA_AUX(NRO,DETALLES) VALUES (NEW.NRO,0);
END^

CREATE TRIGGER TRG_BIDETALLE FOR DETALLE
ACTIVE
BEFORE INSERT
POSITION 0
AS
BEGIN
	IF((SELECT DETALLES FROM FACTURA_AUX WHERE NRO = NEW.NRO) = 3) THEN
		EXCEPTION EX_MAX_DETALLES;
END^

CREATE TRIGGER TRG_AIDETALLE FOR DETALLE
ACTIVE 
AFTER INSERT
POSITION 0
AS
BEGIN
	UPDATE FACTURA_AUX SET DETALLES = DETALLES + 1 WHERE NRO = NEW.NRO;
END^

CREATE TRIGGER TRG_BUDETALLE FOR DETALLE
ACTIVE
BEFORE UPDATE
POSITION 0 
AS
BEGIN
	IF (NEW.NRO <> OLD.NRO) THEN
	BEGIN
		IF((SELECT DETALLES FROM FACTURA_AUX WHERE NRO = NEW.NRO) = 3) THEN
			EXCEPTION EX_MAX_DETALLES;
	END
END^

CREATE TRIGGER TRG_AUDETALLE FOR DETALLE
ACTIVE
AFTER UPDATE
AS
BEGIN
	IF(NEW.NRO <> OLD.NRO) THEN
	BEGIN
		UPDATE FACTURA_AUX SET DETALLES = DETALLES + 1 WHERE NRO = NEW.NRO;
		UPDATE FACTURA_AUX SET DETALLES = DETALLES - 1 WHERE NRO = OLD.NRO;
	END
END^

CREATE TRIGGER ADDETALLES FOR DETALLE
ACTIVE
AFTER DELETE
AS
BEGIN
	UPDATE FACTURA_AUX SET DETALLES = DETALLES - 1 WHERE NRO = OLD.NRO;
END^

SET TERM ; ^
