BEGIN
declare TOTAL_VENTAS int;
declare CANTIDAD_AUX int;
SELECT sum(CANTIDAD) INTO TOTAL_VENTAS FROM VENTA
WHERE VENTA.ID_PRODUCTO = PRODUCTO;
SELECT CANTIDAD INTO CANTIDAD_AUX FROM STOCK
WHERE STOCK.ID_PRODUCTO = PRODUCTO;
set NEW_STOCK = CANTIDAD_AUX - TOTAL_VENTAS ;
select sleep(10) ;
update STOCK set CANTIDAD = NEW_STOCK WHERE STOCK.ID_PRODUCTO = PRODUCTO ;
END
